<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        $userAdmin[] = array(
            array(
            'name' => 'Claudio Souza',
            'cpf' => '21791350500',
            'email' => 'claudiosouza.ascom@alba.ba.gov.br',
            'cadastro' => '925294',
            'email_verified_at' => now(),
            'password' => bcrypt('91316445'),
            'role' => User::USER_ADMIN,
            'depart_id' => null,
            ),
        );

        foreach ($userAdmin as $user) {
            DB::table('users')->insert($user);
        }

        $albas[] = array(
            array(
                'chave' => 'ASSEMBLEIAS LEGISLATIVAS DO BRASIL',
                'nome' => 'UNIÃO NACIONAL DOS LEGISLATIVOS ESTADUAIS',
                'sigla' => 'UNALE',
                'presid' => 'Lídio Lopes',
                'end' => 'SGAS 902, Ed. Athenas, entrada C, lote 104, salas 120 a 131',
                'bairro' => 'Asa Sul',
                'cep' => '70.390-020',
                'cidade' => 'Brasília',
                'uf' => 'DF',
                'tel' => '61 3323-7215/7300',
                'cnpj' => 'null',
                'url' => 'www.unale.org.br',
                'email' => 'unale@unale.org.br',
                'tag' => 'UNIÃO NACIONAL DOS LEGISLATIVOS ESTADUAIS UNALE Lídio Lopes Brasília DF',
            ),
            array(
                'chave' => 'ASSEMBLEIAS LEGISLATIVAS DO BRASIL',
                'nome' => 'ASSEMBLEIA LEGISLATIVA DO ESTADO DO ACRE',
                'sigla' => 'ALEAC',
                'presid' => 'Nicolau Júnior',
                'end' => 'R. Arlindo Porto Leal nº 241',
                'bairro' => 'Centro',
                'cep' => '69.900-904',
                'cidade' => 'Rio Branco',
                'uf' => 'AC',
                'tel' => '68 3213-4020/4021',
                'cnpj' => 'null',
                'url' => 'www.al.ac.leg.br',
                'email' => 'presidencia@al.ac.leg.br/cerimonial.aleac@gmail.com',
                'tag' =>  'ASSEMBLEIA LEGISLATIVA DO ESTADO DO ACRE ALEAC Nicolau Júnior Rio Branco AC',
            ),
            array(
                'chave' => 'ASSEMBLEIAS LEGISLATIVAS DO BRASIL',
                'nome' => 'ASSEMBLEIA LEGISLATIVA DO ESTADO DE ALAGOAS',
                'sigla' => 'AL/AL',
                'presid' => 'Marcelo Victor',
                'end' => 'Praça Dom Pedro II, Palácio Tavares Bastos',
                'bairro' => 'Centro',
                'cep' => '57.020-900',
                'cidade' => 'Maceió',
                'uf' => 'AL',
                'tel' => 'null',
                'cnpj' => 'null',
                'url' => 'www.al.al.leg.br',
                'email' => 'dep.marcelovictor@al.al.leg.br',
                'tag' =>  'ASSEMBLEIA LEGISLATIVA DO ESTADO DE ALAGOAS AL/AL Marcelo Victor Maceió AL',
            ),
            array(
                'chave' => 'ASSEMBLEIAS LEGISLATIVAS DO BRASIL',
                'nome' => 'ASSEMBLEIA LEGISLATIVA DO ESTADO DO AMAZONAS',
                'sigla' => 'ALEAM',
                'presid' => 'Roberto Maia Cidade Filho',
                'end' => 'Av. Mário Ypiranga Monteiro, 3950, Ed. Dep. José J. L. Albuquerque',
                'bairro' => 'Parque 10 de Novembro',
                'cep' => '69.050-030',
                'cidade' => 'Manaus',
                'uf' => 'AM',
                'tel' => '92 3183-4444/4446/4335/4489',
                'cnpj' => 'null',
                'url' => 'www.aleam.gov.br',
                'email' => 'null',
                'tag' =>  'ASSEMBLEIA LEGISLATIVA DO ESTADO DO AMAZONAS ALEAM Roberto Maia Cidade Filho Manaus AM',
            ),
            array(
                'chave' => 'ASSEMBLEIAS LEGISLATIVAS DO BRASIL',
                'nome' => 'ASSEMBLEIA LEGISLATIVA DO ESTADO DO AMAPÁ',
                'sigla' => 'AL/AP',
                'presid' => 'Kaká Barbosa',
                'end' => 'Av. FAB, s/n - Palácio Deputado Nelson Salomão',
                'bairro' => 'Centro',
                'cep' => '68.906-005',
                'cidade' => 'Macapá',
                'uf' => 'AP',
                'tel' => '96 3212-8302/8336',
                'cnpj' => 'null',
                'url' => 'www.al.ap.gov.br',
                'email' => 'presidencia@al.ap.gov.br',
                'tag' =>  'ASSEMBLEIA LEGISLATIVA DO ESTADO DO AMAPÁ AL/AP Kaká Barbosa Macapá AP',
            ),
            array(
                'chave' => 'ASSEMBLEIAS LEGISLATIVAS DO BRASIL',
                'nome' => 'ASSEMBLEIA LEGISLATIVA DO ESTADO DA BAHIA',
                'sigla' => 'ALBA',
                'presid' => 'Adolfo Menezes',
                'end' => 'Av. Luiz Viana Filho, nº 130, Palácio Dep. Luís Eduardo Magalhães',
                'bairro' => 'CAB',
                'cep' => '41.745-000',
                'cidade' => 'Salvador',
                'uf' => 'BA',
                'tel' => '71 3115-4902/4901/4905',
                'cnpj' => 'null',
                'url' => 'www.al.ba.gov.br',
                'email' => 'adolfo.menezes@alba.ba.gov.br',
                'tag' =>  'ASSEMBLEIA LEGISLATIVA DO ESTADO DA BAHIA ALBA Adolfo Menezes Salvador BA',
            ),
            array(
                'chave' => 'ASSEMBLEIAS LEGISLATIVAS DO BRASIL',
                'nome' => 'ASSEMBLEIA LEGISLATIVA DO ESTADO DO CEARÁ',
                'sigla' => 'AL/CE',
                'presid' => 'Evandro Leitão',
                'end' => 'Av. Des. Moreira, 2807, Palácio Gov. Adauto Bezerra',
                'bairro' => 'Dionísio Torres',
                'cep' => '60.170-900',
                'cidade' => 'Fortaleza',
                'uf' => 'CE',
                'tel' => '85 3277-2510/2524/2500',
                'cnpj' => 'null',
                'url' => 'www.al.ce.gov.br',
                'email' => 'secretariaexecutivapres@al.ce.gov.br',
                'tag' =>  'ASSEMBLEIA LEGISLATIVA DO ESTADO DO CEARÁ AL/CE Evandro Leitão Fortaleza CE',
            ),
            array(
                'chave' => 'ASSEMBLEIAS LEGISLATIVAS DO BRASIL',
                'nome' => 'ASSEMBLEIA LEGISLATIVA DO ESTADO DO ESPÍRITO SANTO',
                'sigla' => 'AL/ES',
                'presid' => 'Erick Cabral Musso',
                'end' => 'Av. Américo Buaiz, nº 205',
                'bairro' => 'Enseada do Suá',
                'cep' => '29.050-950',
                'cidade' => 'Vitória',
                'uf' => 'ES',
                'tel' => '27 3382-3710/3500/3590',
                'cnpj' => 'null',
                'url' => 'www.al.es.gov.br',
                'email' => 'presidencia@al.es.gov.br ',
                'tag' =>  'ASSEMBLEIA LEGISLATIVA DO ESTADO DO ESPÍRITO SANTO AL/ES Erick Cabral Musso Vitória ES',
            ),
            array(
                'chave' => 'ASSEMBLEIAS LEGISLATIVAS DO BRASIL',
                'nome' => 'ASSEMBLEIA LEGISLATIVA DO ESTADO DE GOIÁS',
                'sigla' => 'AL/GO',
                'presid' => 'Lissauer Vieira',
                'end' => 'Av. Emival Bueno QG-lote 01, Palácio Maguito Vilela',
                'bairro' => 'Park Lozandes',
                'cep' => '74.884-090',
                'cidade' => 'Goiânia',
                'uf' => 'GO',
                'tel' => '62 3221-3091/3095',
                'cnpj' => 'null',
                'url' => 'www.al.go.leg.br',
                'email' => 'lissauervieira@gmail.com',
                'tag' =>  'ASSEMBLEIA LEGISLATIVA DO ESTADO DE GOIÁS AL/GO Lissauer Vieira Goiânia GO',
            ),
            array(
                'chave' => 'ASSEMBLEIAS LEGISLATIVAS DO BRASIL',
                'nome' => 'ASSEMBLEIA LEGISLATIVA DO ESTADO DO MARANHÃO',
                'sigla' => 'AL/MA',
                'presid' => 'Othelino Neto',
                'end' => 'Av. Jerônimo de Albuquerque, s/nº - Sítio do Rangedor Calhau',
                'bairro' => 'Cohafuma',
                'cep' => '65.071-750',
                'cidade' => 'São Luís',
                'uf' => 'MA',
                'tel' => '98 3269-3000/3001',
                'cnpj' => 'null',
                'url' => 'www.al.ma.gov.br',
                'email' => 'othelinoneto@yahoo.com.br',
                'tag' =>  'ASSEMBLEIA LEGISLATIVA DO ESTADO DO MARANHÃO AL/MA Othelino Neto São Luís MA',
            ),
            array(
                'chave' => 'ASSEMBLEIAS LEGISLATIVAS DO BRASIL',
                'nome' => 'ASSEMBLEIA LEGISLATIVA DO ESTADO DE MINAS GERAIS',
                'sigla' => 'ALMG',
                'presid' => 'Agostinho Célio Andrade Patrus',
                'end' => 'Rua Rodrigues Caldas, nº 30',
                'bairro' => 'Santo Agostinho',
                'cep' => '30.190-921',
                'cidade' => 'Belo Horizonte',
                'uf' => 'MG',
                'tel' => '31 2108-5000/5004',
                'cnpj' => 'null',
                'url' => 'www.almg.gov.br',
                'email' => 'secretaria.presidencia@almg.gov.br',
                'tag' =>  'ASSEMBLEIA LEGISLATIVA DO ESTADO DE MINAS GERAIS ALMG Agostinho Célio Andrade Patrus Belo Horizonte MG',
            ),
            array(
                'chave' => 'ASSEMBLEIAS LEGISLATIVAS DO BRASIL',
                'nome' => 'ASSEMBLEIA LEGISLATIVA DO ESTADO DO MATO GROSSO',
                'sigla' => 'AL/MT',
                'presid' => 'Eduardo Botelho',
                'end' => 'Av. André Maggi, nº 6, setor A',
                'bairro' => 'Centro Político Administrativo',
                'cep' => '78.049-901',
                'cidade' => 'Cuiabá',
                'uf' => 'MT',
                'tel' => '65 3313-6407/6561',
                'cnpj' => 'null',
                'url' => 'www.al.mt.gov.br',
                'email' => 'presidencia.almt@gmail.com',
                'tag' =>  'ASSEMBLEIA LEGISLATIVA DO ESTADO DO MATO GROSSO AL/MT Eduardo Botelho Cuiabá MT',
            ),
            array(
                'chave' => 'ASSEMBLEIAS LEGISLATIVAS DO BRASIL',
                'nome' => 'ASSEMBLEIA LEGISLATIVA DO ESTADO DO MATO GROSSO DO SUL',
                'sigla' => 'AL/MS',
                'presid' => 'Paulo Corrêa',
                'end' => 'Parque dos Poderes, Bloco 09 - Palácio Guaicurus',
                'bairro' => 'Parque dos Poderes',
                'cep' => '79.031-901',
                'cidade' => 'Campo Grande',
                'uf' => 'MS',
                'tel' => '67 3389-4272/6408',
                'cnpj' => 'null',
                'url' => 'www.al.ms.gov.br',
                'email' => 'deputado@deppaulocorrea.com.br',
                'tag' =>  'ASSEMBLEIA LEGISLATIVA DO ESTADO DO MATO GROSSO DO SUL AL/MS Paulo Corrêa Campo Grande MS',
            ),
            array(
                'chave' => 'ASSEMBLEIAS LEGISLATIVAS DO BRASIL',
                'nome' => 'ASSEMBLEIA LEGISLATIVA DO ESTADO DO PARÁ',
                'sigla' => 'ALEPA',
                'presid' => 'Francisco Melo (Chicão)',
                'end' => 'Rua do Aveiro, 130, Praça Dom Pedro II',
                'bairro' => 'Cidade Velha',
                'cep' => '66.020-070',
                'cidade' => 'Belém',
                'uf' => 'PA',
                'tel' => '91 3213- 4202/4226',
                'cnpj' => 'null',
                'url' => 'www.alepa.pa.gov.br',
                'email' => 'presidencia@alepa.pa.gov.br',
                'tag' =>  'ASSEMBLEIA LEGISLATIVA DO ESTADO DO PARÁ ALEPA Francisco Melo (Chicão) Belém PA',
            ),
            array(
                'chave' => 'ASSEMBLEIAS LEGISLATIVAS DO BRASIL',
                'nome' => 'ASSEMBLEIA LEGISLATIVA DO ESTADO DA PARAÍBA',
                'sigla' => 'AL/PB',
                'presid' => 'Adriano César Galdino de Araújo',
                'end' => 'Praça João Pessoa, s/n - Casa de Epitácio Pessoa',
                'bairro' => 'Centro',
                'cep' => '58.013-900',
                'cidade' => 'João Pessoa',
                'uf' => 'PB',
                'tel' => '83 3214-1226/4638',
                'cnpj' => 'null',
                'url' => 'www.al.pb.leg.br',
                'email' => 'presidencia@al.pb.leg.br',
                'tag' =>  'ASSEMBLEIA LEGISLATIVA DO ESTADO DA PARAÍBA AL/PB Adriano César Galdino de Araújo João Pessoa PB',
            ),
            array(
                'chave' => 'ASSEMBLEIAS LEGISLATIVAS DO BRASIL',
                'nome' => 'ASSEMBLEIA LEGISLATIVA DO ESTADO DE PERNAMBUCO',
                'sigla' => 'ALEPE',
                'presid' => 'Eriberto Medeiros',
                'end' => 'Rua da União, 439, Palácio Joaquim Nabuco',
                'bairro' => 'Boa Vista',
                'cep' => '50.050-909',
                'cidade' => 'Recife',
                'uf' => 'PE',
                'tel' => '81 3183-2246/2233/2211',
                'cnpj' => 'null',
                'url' => 'www.alepe.pe.gov.br',
                'email' => 'presidente@alepe.pe.gov.br ',
                'tag' =>  'ASSEMBLEIA LEGISLATIVA DO ESTADO DE PERNAMBUCO ALEPE Eriberto Medeiros Recife PE',
            ),
            array(
                'chave' => 'ASSEMBLEIAS LEGISLATIVAS DO BRASIL',
                'nome' => 'ASSEMBLEIA LEGISLATIVA DO ESTADO DO PIAUÍ',
                'sigla' => 'ALEPI',
                'presid' => 'Themistócles de Sampaio Pereira Filho',
                'end' => 'Av. Marechal Castelo Branco, 201, Palácio Petrônio Portela',
                'bairro' => 'Cabral',
                'cep' => '64.000-810',
                'cidade' => 'Teresina',
                'uf' => 'PI',
                'tel' => '86 3133-3182/3184',
                'cnpj' => 'null',
                'url' => 'www.alepi.pi.gov.br',
                'email' => 'presidenciaassembleiapiaui@gmail.com',
                'tag' =>  'ASSEMBLEIA LEGISLATIVA DO ESTADO DO PIAUÍ ALEPI Themistócles de Sampaio Pereira Filho Teresina PI',
            ),
            array(
                'chave' => 'ASSEMBLEIAS LEGISLATIVAS DO BRASIL',
                'nome' => 'ASSEMBLEIA LEGISLATIVA DO ESTADO DO PARANÁ',
                'sigla' => 'ALEP',
                'presid' => 'Ademar Luiz Traiano',
                'end' => 'Pça N. Sra. do Salete, s/n',
                'bairro' => 'Centro Cívico Aníbal Khoury',
                'cep' => '80.530-911',
                'cidade' => 'Curitiba',
                'uf' => 'PR',
                'tel' => '41 3350-4040/4041/3350-4000',
                'cnpj' => 'null',
                'url' => 'www.alep.pr.gov.br',
                'email' => 'deputadotraiano@gmail.com',
                'tag' =>  'ASSEMBLEIA LEGISLATIVA DO ESTADO DO PARANÁ ALEP Ademar Luiz Traiano Curitiba PR',
            ),
            array(
                'chave' => 'ASSEMBLEIAS LEGISLATIVAS DO BRASIL',
                'nome' => 'ASSEMBLEIA LEGISLATIVA DO ESTADO DO RIO DE JANEIRO',
                'sigla' => 'ALERJ',
                'presid' => 'André Luiz Ceciliano',
                'end' => 'Rua México, nº 125 8º andar',
                'bairro' => 'Centro',
                'cep' => '20.031-144',
                'cidade' => 'Rio de Janeiro',
                'uf' => 'RJ',
                'tel' => '21 2588-1477/8443',
                'cnpj' => 'null',
                'url' => 'www.alerj.rj.gov.br',
                'email' => 'presidencia@alerj.rj.gov.br',
                'tag' =>  'ASSEMBLEIA LEGISLATIVA DO ESTADO DO RIO DE JANEIRO ALERJ André Luiz Ceciliano Rio de Janeiro RJ',
            ),
            array(
                'chave' => 'ASSEMBLEIAS LEGISLATIVAS DO BRASIL',
                'nome' => 'ASSEMBLEIA LEGISLATIVA DO ESTADO DO RIO GRANDE DO NORTE',
                'sigla' => 'AL/RN',
                'presid' => 'Ezequiel Ferreira de Souza',
                'end' => 'Praça 7 de Setembro, s/n, Palácio José Augusto',
                'bairro' => 'Cidade Alta',
                'cep' => '59.025-300',
                'cidade' => 'Natal',
                'uf' => 'RN',
                'tel' => '84 3232-5763/5764',
                'cnpj' => 'null',
                'url' => 'www.al.rn.gov.br',
                'email' => 'ezequielferreira@rn.gov.br',
                'tag' =>  'ASSEMBLEIA LEGISLATIVA DO ESTADO DO RIO GRANDE DO NORTE AL/RN Ezequiel Ferreira de Souza Natal RN',
            ),
            array(
                'chave' => 'ASSEMBLEIAS LEGISLATIVAS DO BRASIL',
                'nome' => 'ASSEMBLEIA LEGISLATIVA DO ESTADO DE RONDÔNIA',
                'sigla' => 'ALE/RO',
                'presid' => 'Alex Mendonça Alves',
                'end' => 'Av. Saquar, 2562, Palácio Marechal Rondon',
                'bairro' => 'Olaria',
                'cep' => '76.801-189',
                'cidade' => 'Porto Velho',
                'uf' => 'RO',
                'tel' => '69 3218-3740/5605',
                'cnpj' => 'null',
                'url' => 'www.ale.ro.leg.br',
                'email' => 'cerimonial@ale.ro.gov.br',
                'tag' =>  'ASSEMBLEIA LEGISLATIVA DO ESTADO DE RONDÔNIA ALE/RO Alex Mendonça Alves Porto Velho RO',
            ),
            array(
                'chave' => 'ASSEMBLEIAS LEGISLATIVAS DO BRASIL',
                'nome' => 'ASSEMBLEIA LEGISLATIVA DO ESTADO DE RORAIMA',
                'sigla' => 'AL/RR',
                'presid' => 'Jalser Renier Padilha',
                'end' => 'Praça do Centro Cívico, 202',
                'bairro' => 'Centro',
                'cep' => '69.301-380',
                'cidade' => 'Boa Vista',
                'uf' => 'RR',
                'tel' => '95 4009-5546/5567',
                'cnpj' => 'null',
                'url' => 'www.al.rr.leg.br',
                'email' => 'presidencia@al.rr.gov.br',
                'tag' =>  'ASSEMBLEIA LEGISLATIVA DO ESTADO DE RORAIMA AL/RR Jalser Renier Padilha Boa Vista RR',
            ),
            array(
                'chave' => 'ASSEMBLEIAS LEGISLATIVAS DO BRASIL',
                'nome' => 'ASSEMBLEIA LEGISLATIVA DO ESTADO DO RIO GRANDE DO SUL',
                'sigla' => 'AL/RS',
                'presid' => 'Valdeci Oliveira',
                'end' => 'Praça Marechal Deodoro, 101, 2º andar - Palácio Farroupilha',
                'bairro' => 'Centro',
                'cep' => '90.010-300',
                'cidade' => 'Porto Alegre',
                'uf' => 'RS',
                'tel' => '51 3210-2932/2071',
                'cnpj' => 'null',
                'url' => 'www.al.rs.gov.br',
                'email' => 'presidencia@al.rs.gov.br',
                'tag' =>  'ASSEMBLEIA LEGISLATIVA DO ESTADO DO RIO GRANDE DO SUL AL/RS Valdeci Oliveira Porto Alegre RS',
            ),
            array(
                'chave' => 'ASSEMBLEIAS LEGISLATIVAS DO BRASIL',
                'nome' => 'ASSEMBLEIA LEGISLATIVA DO ESTADO DE SANTA CATARINA',
                'sigla' => 'ALESC',
                'presid' => 'Moaci Sopelsa',
                'end' => 'Av. Dr. Jorge Luz Fontes, 310, Palácio Barriga-Verde',
                'bairro' => 'Pça Tancredo Neves/Centro',
                'cep' => '88.020-900',
                'cidade' => 'Florianópolis',
                'uf' => 'SC',
                'tel' => '48 3221-2611/2612',
                'cnpj' => 'null',
                'url' => 'www.alesc.sc.gov.br',
                'email' => 'secgeral@alesc.sc.gov.br',
                'tag' =>  'ASSEMBLEIA LEGISLATIVA DO ESTADO DE SANTA CATARINA ALESC Moaci Sopelsa Florianópolis SC',
            ),
            array(
                'chave' => 'ASSEMBLEIAS LEGISLATIVAS DO BRASIL',
                'nome' => 'ASSEMBLEIA LEGISLATIVA DO ESTADO DE SERGIPE',
                'sigla' => 'AL/SE',
                'presid' => 'Luciano Bispo de Lima',
                'end' => 'Av. Ivo do Prado, s/n, Palácio Gov. João Alves Filho',
                'bairro' => 'Centro',
                'cep' => '49.010-050',
                'cidade' => 'Aracaju',
                'uf' => 'SE',
                'tel' => '79 3216-6655/6695',
                'cnpj' => 'null',
                'url' => 'www.al.se.leg.br',
                'email' => 'dep.lucianobispo@al.se.leg.br',
                'tag' =>  'ASSEMBLEIA LEGISLATIVA DO ESTADO DE SERGIPE AL/SE Luciano Bispo de Lima Aracaju SE',
            ),
            array(
                'chave' => 'ASSEMBLEIAS LEGISLATIVAS DO BRASIL',
                'nome' => 'ASSEMBLEIA LEGISLATIVA DO ESTADO DE SÃO PAULO',
                'sigla' => 'AL/SP',
                'presid' => 'Carlos Pignatari',
                'end' => 'Av. Pedro Álvares Cabral, 201, Palácio 9 de Julho',
                'bairro' => 'Parque do Ibirapuera',
                'cep' => '040.97-900',
                'cidade' => 'São Paulo',
                'uf' => 'SP',
                'tel' => '11 3886-6217/6218/6200/3886-6000',
                'cnpj' => 'null',
                'url' => 'www.al.sp.gov.br',
                'email' => 'carlaopignatari@al.sp.gov.br',
                'tag' =>  'ASSEMBLEIA LEGISLATIVA DO ESTADO DE SÃO PAULO AL/SP Carlos Pignatari São Paulo SP',
            ),
            array(
                'chave' => 'ASSEMBLEIAS LEGISLATIVAS DO BRASIL',
                'nome' => 'ASSEMBLEIA LEGISLATIVA DO ESTADO DE TOCANTINS',
                'sigla' => 'AL/TO',
                'presid' => 'Antônio Andrade',
                'end' => 'Pça dos Girassóis, s/n, Palácio Deputado João D´abreu',
                'bairro' => 'Centro',
                'cep' => '77.001-902',
                'cidade' => 'Palmas',
                'uf' => 'TO',
                'tel' => '63 3212-5055/5080',
                'cnpj' => 'null',
                'url' => 'www.al.to.leg.br',
                'email' => 'presidencia@al.to.leg.br',
                'tag' =>  'ASSEMBLEIA LEGISLATIVA DO ESTADO DE TOCANTINS AL/TO Antônio Andrade Palmas TO',
            ),
            array(
                'chave' => 'ASSEMBLEIAS LEGISLATIVAS DO BRASIL',
                'nome' => 'CÂMARA LEGISLATIVA DO DISTRITO FEDERAL',
                'sigla' => 'CL/DF',
                'presid' => 'Rafael Prudente',
                'end' => 'Praça Municipal, Qd. 02, Lote 05',
                'bairro' => 'Setor Gráfico',
                'cep' => '70.094-902',
                'cidade' => 'Brasília',
                'uf' => 'DF',
                'tel' => '61 3348-8000/3348-8766/8610/8002',
                'cnpj' => 'null',
                'url' => 'www.cl.df.gov.br',
                'email' => 'agenda.deputadorafaelprudente@gmail.com',
                'tag' =>  'CÂMARA LEGISLATIVA DO DISTRITO FEDERAL CL/DF Rafael Prudente Brasília DF',
            ),
        );
        foreach ($albas as $alba){
            DB::table('albas')->insert($alba);
        }
    }
}
